name = "orum-zamin-behsazan"
main = "src/index.js"
compatibility_date = "2024-09-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "OZ_KV"
id = "71d57c45837d4934886eb0a5b2b5e4cf"
